EquilibriumCore/Models/Skills.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EquilibriumCore.Models
{
    public class Skills
    {
        [Key] public int ID { get; set; }
        public string superCat { get; set; }
        public string cat { get; set; }
        public string Name { get; set; }
        public string Effect { get; set; }
        public int levelMax { get; set; }
        public string Tags { get; set; }
        public string Ignore { get; set; }
        [NotMapped] public string currentEffect { get => getEffect(); }

        [NotMapped] int currentLevel;
        [NotMapped] public int CurrentLevel {get =>  currentLevel;set => setLevel(value);}
        public Skills()
        {
            this.superCat = "";
            this.cat = "";
            Name = "";
            Effect = "";
            this.levelMax = 0;
            Tags = "";
        }
        public Skills(string superCat, string cat, string name, string effect, int levelMax)
        {
            this.superCat = superCat;
            this.cat = cat;
            Name = name;
            Effect = effect;
            this.levelMax = levelMax;
            Tags = "";
        }
        public void setLevel(int value)
        {
            if(value>levelMax)
            {
                currentLevel = levelMax;
            }else
            {
                currentLevel = value;
            }
        }
        public string getEffect()
        {
            string s = "";
            string[] ignored;
            if (Ignore != null && Ignore != ""  && Ignore.Contains(';'))
            {
                 ignored = Ignore.Split(";");
            }else if (Ignore != null && Ignore != "")
            {
                ignored = new string[1];
                ignored[0] = Ignore;
            } else
            {
                ignored = new string[0];
            }
            foreach (char c in Effect)
            {
                int outVal;
                if(int.TryParse(c.ToString(),out outVal) && !ignored.Contains( c.ToString()))
                {
                    s += outVal * CurrentLevel;
                }else
                {
                    s += c;
                }
            }
            return s;
        }
        public string getIDComposed()
        {
            return superCat + " " + cat + " " + Tags;
        }
    }
}

EquilibriumCore/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquilibriumCore.Data;
using EquilibriumCore.Models;
using Microsoft.AspNetCore.Authorization;

namespace EquilibriumCore.Controllers
{
    
    public class SkillsController : Controller
    {
        private readonly DataContext _context;

        public SkillsController(DataContext context)
        {
            _context = context;
        }

        // GET: Skills
        public async Task<IActionResult> Index(string? sCat, string? cat )
        {
            Console.WriteLine(sCat);
            List<Skills> filtered = await _context.Skills.ToListAsync();
            Dictionary<string, List<string>> catDictio = new Dictionary<string, List<string>>();

            catDictio = filtered.Select((s) => (s.superCat,s.cat)).Distinct().GroupBy(x=>x.superCat,x=>x.cat).ToDictionary((x)=>x.Key , (x)=>x.ToList());



            if (sCat != null && sCat != "")
            {
                filtered = filtered.Where((s) => s.superCat.Contains(sCat)).ToList();
                if (cat != null && cat != "")
                {
                    filtered = filtered.Where((s) => s.cat.Contains(cat)).ToList();
                }
            }
            ViewBag.catDictio = catDictio;
            ViewBag.filtered = filtered;

            return View();
        }

        // GET: Skills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skills = await _context.Skills
                .FirstOrDefaultAsync(m => m.ID == id);
            if (skills == null)
            {
                return NotFound();
            }

            return View(skills);
        }

        public async Task<IActionResult> Select(int? FP )
        {
            ViewBag.FP = FP;
            List<string> Tags = new List<string>();
            var f = _context.Feuilles.Find(FP);
            string[] uTag;
            ViewBag.uTag = null;
           if (f.skills != null)
            {
                uTag = f.skills.Split(";", StringSplitOptions.RemoveEmptyEntries);
                var u = uTag.Select((a) => _context.Skills.Find(int.Parse(a)));
                u = u.Distinct();
                var tmp = u.SelectMany((a) => a.Tags.Split(' ', StringSplitOptions.RemoveEmptyEntries)).GroupBy(a => a).OrderByDescending((a) => a.Count());
                ViewBag.uTag = tmp.Select(a => a.Key).ToArray();
            }
          
          
               // Dictionary<string, int> CharacterTags;
               Tags = _context.Skills.Select((a) => a.Tags).Where((a) => a != null && a != "").ToList();
            Tags = String.Join(' ', Tags).Split(' ',StringSplitOptions.RemoveEmptyEntries).Distinct().ToList();  //.SelectMany(a => a.Split(" ",StringSplitOptions.RemoveEmptyEntries)).Distinct().ToList();
         
            List<string> Cats = _context.Skills.Select((a) => a.cat).Distinct().ToList();
            List<string> SupCats = _context.Skills.Select((a) => a.superCat).Distinct().ToList();
            ViewBag.Tags = Tags.OrderBy((a) => a);
            ViewBag.Cats = Cats.OrderBy((a)=>a);
            ViewBag.SupCats = SupCats.OrderBy((a) => a);
            return View(await _context.Skills.ToListAsync());
        }
        public async Task<IActionResult> Selected(int? id,int? FP)
        {
                       
            return RedirectToAction("AddSkillsFP", "FeuillePersonnages", new { id = FP });
        }

        // GET: Skills/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Skills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ID,superCat,cat,Name,Effect,levelMax,Tags")] Skills skills)
        {
            if (ModelState.IsValid)
            {
                string textOld = "";
                string textNew = "Add : " + skills.Name + " - Level : " + skills.levelMax + " - " + skills.Effect;
                if (textOld != textNew)
                {
                    Modification modif = new Modification() { Categorie = "Add", SousCategorie = "Skills - " + skills.superCat, IDUpdate = _context.Update.Where((a) => a.Sortie == _context.Update.Max((b) => b.Sortie)).First().ID };
                    modif.TexteOld = textOld;
                    modif.TexteNew = textNew;
                    _context.Add(modif);
                }
                _context.Add(skills);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(skills);
        }

        // GET: Skills/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skills = await _context.Skills.FindAsync(id);
            if (skills == null)
            {
                return NotFound();
            }
            return View(skills);
        }

        // POST: Skills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,superCat,cat,Name,Effect,levelMax,Tags,Ignore")] Skills skills)
        {
            if (id != skills.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Skills old = _context.Skills.AsNoTracking().First((a) => a.ID == skills.ID);
                    
                    string textOld = "Modification : " + old.Name + " - Level : " + old.levelMax + " - " + old.Effect;
                    string textNew = "Modification : " + skills.Name + " - Level : " + skills.levelMax + " - " + skills.Effect;
                    if(textOld != textNew)
                    {
                        Modification modif = new Modification() { Categorie = "Modification", SousCategorie = "Skills - " + skills.superCat, IDUpdate = _context.Update.Where((a) => a.Sortie == _context.Update.Max((b) => b.Sortie)).First().ID };
                        modif.TexteOld = textOld;
                        modif.TexteNew = textNew;                        
                            _context.Add(modif);
                    }

                    
                    _context.Update(skills);
                    
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkillsExists(skills.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(skills);
        }

        // GET: Skills/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skills = await _context.Skills
                .FirstOrDefaultAsync(m => m.ID == id);
            if (skills == null)
            {
                return NotFound();
            }

            return View(skills);
        }

        // POST: Skills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Skills old = _context.Skills.AsNoTracking().First((a) => a.ID == id);
            string textOld = "Delete : " + old.Name + " - Level : " + old.levelMax + " - " + old.Effect;
            string textNew = "";
            if (textOld != textNew)
            {
                Modification modif = new Modification() { Categorie = "Delete", SousCategorie = "Skills - " + old.superCat, IDUpdate = _context.Update.Where((a) => a.Sortie == _context.Update.Max((b) => b.Sortie)).First().ID };
                modif.TexteOld = textOld;
                modif.TexteNew = textNew;
                _context.Add(modif);
            }

            var skills = await _context.Skills.FindAsync(id);
            _context.Skills.Remove(skills);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Admin()
        {
            return View("Index Admin",await _context.Skills.ToListAsync());
        }
        private bool SkillsExists(int id)
        {
            return _context.Skills.Any(e => e.ID == id);
        }
    }
}

EquilibriumCore/Views/Skills/Create.cshtml
@model EquilibriumCore.Models.Skills

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Skills</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="superCat" class="control-label"></label>
                <input asp-for="superCat" class="form-control" />
                <span asp-validation-for="superCat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cat" class="control-label"></label>
                <input asp-for="cat" class="form-control" />
                <span asp-validation-for="cat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Effect" class="control-label"></label>
                <input asp-for="Effect" class="form-control" />
                <span asp-validation-for="Effect" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="levelMax" class="control-label"></label>
                <input asp-for="levelMax" class="form-control" />
                <span asp-validation-for="levelMax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EquilibriumCore/Views/Skills/Delete.cshtml
@model EquilibriumCore.Models.Skills

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Skills</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.superCat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.superCat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Effect)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Effect)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.levelMax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.levelMax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tags)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EquilibriumCore/Views/Skills/Details.cshtml
@model EquilibriumCore.Models.Skills

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Skills</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.superCat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.superCat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Effect)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Effect)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.levelMax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.levelMax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tags)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EquilibriumCore/Views/Skills/Edit.cshtml
@model EquilibriumCore.Models.Skills

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Skills</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="superCat" class="control-label"></label>
                <input asp-for="superCat" class="form-control" />
                <span asp-validation-for="superCat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cat" class="control-label"></label>
                <input asp-for="cat" class="form-control" />
                <span asp-validation-for="cat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Effect" class="control-label"></label>
                <input asp-for="Effect" class="form-control" />
                <span asp-validation-for="Effect" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="levelMax" class="control-label"></label>
                <input asp-for="levelMax" class="form-control" />
                <span asp-validation-for="levelMax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ignore" class="control-label"></label>
                <input asp-for="Ignore" class="form-control" />
                <span asp-validation-for="Ignore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EquilibriumCore/Views/Skills/Index Admin.cshtml
@model IEnumerable<EquilibriumCore.Models.Skills>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.superCat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Effect)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.levelMax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tags)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.superCat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Effect)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.levelMax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tags)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>


</table>

EquilibriumCore/Views/Skills/Index.cshtml
@model EquilibriumCore.Models.Skills

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    Dictionary<string, List<string>> category = ViewBag.catDictio;
    List<EquilibriumCore.Models.Skills> skillsF = ViewBag.filtered;
}
<link rel="stylesheet" href="~/css/site.css" />
<div class="wrapper">
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3>Classes Skills</h3>
        </div>
        <ul>
            <li><h3> <a asp-area="" asp-controller="Skills" asp-action="Index"> All  </a></h3></li>

            @foreach (var sCat in category.Keys)
            {
                <li><h3> <a href="?sCat=@Html.Raw(sCat.Count() > 0 ? sCat.Remove(0, 1) : sCat)"> @Html.Raw(sCat.Count() > 0 ? sCat.Remove(0, 1) : sCat) </a></h3></li>

                List<string> Cats = category[sCat];
                @foreach (var Cat in Cats)
                {
                    <li> <h4><a href="?sCat=@Html.Raw(sCat.Count() > 0 ? sCat.Remove(0, 1) : sCat)&cat=@Html.Raw(Cat.Count() > 0 ? Cat.Remove(0, 1) : Cat)"> &nbsp; @Html.Raw(Cat.Count() > 0 ? Cat.Remove(0, 1) : Cat)</a></h4> </li>
                }
            }
        </ul>
    </nav>
    <div id="content">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Effect
                    </th>
                    <th>
                        Level Max
                    </th>
                    <th>
                        Tags
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Skills s in skillsF)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => s.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => s.Effect)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => s.levelMax)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => s.Tags)
                    </td>
                </tr>

                }
            </tbody>
            </table>
        </div>
</div>

EquilibriumCore/Views/Skills/Select.cshtml
@model IEnumerable<EquilibriumCore.Models.Skills>

@{
    ViewData["Title"] = "Select";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Select One ...</h2>

<h4> Tag you have : </h4>
@{int i = 0; }
@if(ViewBag.uTag != null)
{


@foreach (string item in ViewBag.uTag)
{
    i++;
    int g = 100 + (140 / ViewBag.uTag.Length) * i;

    <button class="btn" style="background-color : rgb(@g,240 ,0) " onclick="SetFilter('@item')"> @item </button>
}
    }
<br />
<h4>Or search: </h4>
<br />
<select id="filterSC" onchange="Filter()">
    <option value=""></option>
    @foreach (string item in ViewBag.SupCats)
    {
        <option value="@item">@item</option>
    }
</select>
<select id="filterC" onchange="Filter()">
    <option value=""></option>
    @foreach (string item in ViewBag.Cats)
    {
        <option value="@item">@item</option>
    }
</select>
<select id="filterT" onchange="Filter()">
    <option value=""></option>
    @foreach (string item in ViewBag.Tags)
    {
        <option value="@item">@item</option>
    }
</select>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Effect)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.levelMax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tags)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="Skills" id="@item.getIDComposed()">

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Effect)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.levelMax)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tags)
                </td>
                <td>
                    <a asp-action="AddSkillsFP" asp-controller="FeuillePersonnages" asp-route-id="@ViewBag.FP" asp-all-route-data=' new Dictionary<string, string> { {"SkillId" ,item.ID.ToString() }, {"id", ViewBag.FP.ToString() } }; '>Selected</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    function Filter() {
        // Declare variables
        var ul, li, i;
        filterOnSC = document.getElementById("filterSC").value;
        filterOnC = document.getElementById("filterC").value;
        filterOnT = document.getElementById("filterT").value;
        li = document.getElementsByClassName("Skills");



        // Loop through all list items, and hide those who don't match the search query
        for (i = 0; i < li.length; i++) {
            var s = li[i].id.split(" ");
            var tagok = false;
            var COK = false;
            var SCOK = false;

            if ((filterOnSC == "" || s[0] == filterOnSC)) {
                COK = true;
                // console.log(s[0] + " == " + filterOnSC + (s[0] == filterOnSC));
            }
            if ((filterOnC == "" || s[1] == filterOnC)) {
                // console.log(s[1] + " == " + filterOnC + (s[1] == filterOnC));
                SCOK = true;
            }
            if ((filterOnT != "")) {

                for (var j = 0; j < s.length; j++) {

                    if ((filterOnT == s[j])) //
                    {

                        tagok = true;
                    }


                }

            } else {
                tagok = true;
            }

            if (COK && SCOK && tagok) {
                // console.log(COK + " " + SCOK + " " + tagok)
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }


        }
    }
    function SetFilter(val) {
        document.getElementById("filterT").value = val;
        Filter();
    }
</script>